models/User.php
<?php
namespace app\models;
use Yii;
use \yii\db\ActiveRecord;
use \yii\web\IdentityInterface;
use \yii\base\NotSupportedException;
use \yii\behaviors\TimestampBehavior;

class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE  = 10;
    public $arquivo;
    public static function tableName()
    {
        return 'user';
    }
  
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
  
    public function rules()
    {
        return [
            [['matricula', 'status', 'user_create'], 'integer'],
            [['data_create', 'data_update', 'updated_at', 'created_at'], 'safe'],
            [['authKey'], 'string'],
            [['username', 'nome'], 'string', 'max' => 45],
            [['email', 'passwordHash', 'passwordResetToken'], 'string', 'max' => 255],
            [['email'], 'unique'],
            [['username'], 'unique'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
            [['user_create'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_create' => 'id']],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'email' => 'Email',
            'passwordHash' => 'Password Hash',
            'passwordResetToken' => 'Password Reset Token',
            'matricula' => 'Matricula',
            'nome' => 'Nome',
            'cpf' => 'Cpf',
            'celular' => 'Celular',
            'status' => 'Status',
            'data_create' => 'Data Criação',
            'user_create' => 'User Create',
            'data_update' => 'Data Atualização',
            'authKey' => 'Auth Key',
            'foto' => 'Foto',
        ];
    }
    public function scenarios()
    {
        $scenarios = parent::scenarios();

        return $scenarios;
    }

    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }
   
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
   
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }
  
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email, 'status' => self::STATUS_ACTIVE]);
    }
  
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }
        return static::findOne([
            'passwordResetToken' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }
  
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }
   
    public function getId()
    {
        return $this->id;
    }
    
    public function getAuthKey()
    {
        return $this->authKey;
    }
    
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }
  
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->passwordHash);
    }
    
    public function setPassword($password)
    {
        $this->passwordHash = Yii::$app->security->generatePasswordHash($password);
    }
   
    public function generateAuthKey()
    {
        $this->authKey = Yii::$app->security->generateRandomString();
    }
   
    public function generatePasswordResetToken()
    {
        $this->passwordResetToken = Yii::$app->security->generateRandomString() . '_' . time();
    }
   
    public function removePasswordResetToken()
    {
        $this->passwordResetToken = null;
    }
    public function requestPasswordResetToken($id)
    {
        $user = User::findOne([
            'status' => User::STATUS_ACTIVE,
            'id' => $id,
        ]);
        if (!$user) {
            return false;
        }
        if (!User::isPasswordResetTokenValid($user->passwordResetToken)) {
            $user->generatePasswordResetToken();
        }
        if (!$user->save()) {
            return false;
        }
        return $user->passwordResetToken;
    }
   
    public function getCompromissos()
    {
        return $this->hasMany(Compromisso::className(), ['user_id' => 'id']);
    }

    public function getOportunidades()
    {
        return $this->hasMany(Oportunidade::className(), ['user_id' => 'id']);
    }

    public function getCarteira()
    {
        return $this->hasOne(Carteira::className(), ['id' => 'carteira_id']);
    }

    public function getUserCreate()
    {
        return $this->hasOne(User::className(), ['id' => 'user_create']);
    }

    public function getUsers()
    {
        return $this->hasMany(User::className(), ['user_create' => 'id']);
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;
use app\models\Lead;
use yii\filters\AccessControl;

class UserController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['delete', 'index','view','update','create'],
                'rules' => [
                    [
                        'actions' => ['delete', 'index','view','update','create'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['register', 'recovery'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

   
    public function actionView($id) {
        $this->layout = '@app/views/layouts/dashboard.php';
        $user = \Yii::$app->user->identity;
        $leads = count(Lead::find()
                ->select('id')
                ->distinct('id')
                ->where(['status'=>10,'Carteira_id'=>$user->carteira_id])
                ->all());
        $usuarios = count(User::find()->where(['status'=>10,'user_create'=>Yii::$app->user->identity->id])->all());
        
        return $this->render('view', [
                    'model' => $this->findModel($id),
                    'usuarios'=>$usuarios,
                    'leads'=>$leads
        ]);
    }

    public function actionRegister() {
        $model = new User();

        if ($model->load(Yii::$app->request->post())) {
            $model->setPassword($model->passwordHash);
            $model->generatePasswordResetToken();
            $model->generateAuthKey();
            $model->data_create = date('Y-m-d H:i:s');
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Registro realizado com sucesso.');
                return $this->redirect(['default/index']);
            } else {
                Yii::$app->session->setFlash('error', 'Erro no registro.');
                return $this->redirect(['default/index']);
            }
        } else {

            return $this->render('register', [
                        'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $status = '';
        if($model->status)
        {
           $model->status = 0;
           $status = 'excluido';
        }
        else
        {
           $model->status = 10; 
           $status = 'reativado';
        }
        
        if (!$model->save()) {
            ddd($model->getErrors());
        }
        if($model->id == \Yii::$app->user->identity->id)
        {
            Yii::$app->session->setFlash('success', "Conta excluida com sucesso.");
            Yii::$app->user->logout();
            return $this->redirect(['default/index']);
        }
        else
        {
            Yii::$app->session->setFlash('success', "Usuário {$status} com sucesso.");
            return $this->redirect(['index']);
        }
    }

    protected function findModel($id) {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionRecovery($email = null) {

        $model = new User;

        if (Yii::$app->request->post()) {

            $post = Yii::$app->request->post()['User'];

            $model = User::findByEmail($post['email']);
            if (!$model) {
                $model = new User;
                Yii::$app->session->setFlash('error', 'Usuário não encontrado.');
                return $this->render('recovery', [
                            'model' => $model,
                ]);
            }

            $alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890';
            $pass = []; //remember to declare $pass as an array
            $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
            for ($i = 0; $i < 8; $i++) {
                $n = rand(0, $alphaLength);
                $pass[] = $alphabet[$n];
            }

            $model->setPassword(implode($pass));
            if (!$model->save()) {
                ddd($model->getErrors());
            }

            Yii::$app->mailer->compose()
                    ->setFrom('servicos.ti@grupostudio.com.br')
                    ->setTo($model->email)
                    ->setSubject('Sua senha nova é: ' . implode($pass))
                    ->send();
            Yii::$app->session->setFlash('success', 'Senha enviada para seu e-mail.');
            return $this->redirect(['default/index']);
        }

        return $this->render('recovery', [
                    'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $this->layout = '@app/views/layouts/dashboard.php';
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            
            $model->data_update = date('Y-m-d H:i:s');
            $data = date('d-m-o_H-i-s');
            if (!file_exists('images/foto_usuario')) {
                $path = 'images/foto_usuario';
                FileHelper::createDirectory($path);
            } else {
                $path = 'images/foto_usuario';
            }
            
            $arquivo = UploadedFile::getInstance($model, 'arquivo');
            if ($arquivo) {
                $valida_nome = explode('.', $arquivo->name);

                $arquivo->name = $data . '.' . end($valida_nome);
                $model->foto = $arquivo->name;

                if ($arquivo->saveAs($path . '/' . $arquivo->name)) {
                    if ($model->save()) {
                        Yii::$app->session->setFlash('success', 'Atualizado com sucesso.');
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'Houve um problema ao salvar.');
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Atualizado com sucesso.');
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }
    
    public function actionCreate($id) {
        $this->layout = '@app/views/layouts/dashboard.php';
        $model = new User;
        
        if ($model->load(Yii::$app->request->post())) {
            
            $model->setPassword($model->passwordHash);
            $model->generatePasswordResetToken();
            $model->generateAuthKey();
            $model->data_update = date('Y-m-d H:i:s');
            $model->data_create = date('Y-m-d H:i:s');
            $model->user_create = \Yii::$app->user->identity->id;
            
            $data = date('d-m-o_H-i-s');
            if (!file_exists('images/foto_usuario')) {
                $path = 'images/foto_usuario';
                FileHelper::createDirectory($path);
            } else {
                $path = 'images/foto_usuario';
            }
            
            $arquivo = UploadedFile::getInstance($model, 'arquivo');
            if ($arquivo) {
                $valida_nome = explode('.', $arquivo->name);

                $arquivo->name = $data . '.' . end($valida_nome);
                $model->foto = $arquivo->name;

                if ($arquivo->saveAs($path . '/' . $arquivo->name)) {
                    if ($model->save()) {
                        Yii::$app->session->setFlash('success', 'Criado com sucesso.');
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'Houve um problema na criação.');
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Criado com sucesso.');
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    public function actionIndex() {
        $this->layout = '@app/views/layouts/dashboard.php';
        $model = \Yii::$app->user->identity;
        $usuarios = count(User::find()->where(['user_create'=>Yii::$app->user->identity->id])->all());
        
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'usuarios'=>$usuarios,
                    'model'=>$model
        ]);
    }

}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nome')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cpf')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'celular')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ativo')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/_form_1.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\User */

$this->title = ($model->isNewRecord)? "Usuário Criar" : "Usuário Atualizar";
?>
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Usuário
            <small><?= ($model->isNewRecord)? "Criar" : "Atualizar" ?></small>
        </h1>
        <ol class="breadcrumb">
            <!--<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Início</a></li>-->
        </ol>
    </section>
    <?php $form = ActiveForm::begin(); ?>
    <section class="content">
        <section class="content">
            <div class="box">
                <div class="box-header with-border">
                    <div class="form-group">
                        <?=
                        Html::a("Voltar", ['user/view', 'id' => ($model->id)?$model->id:$_GET['id']], ['class' => 'btn btn-light']);
                        ?>
                        <?= Html::submitButton('Salvar', ['class' => 'btn btn-success pull-right']) ?>
                    </div>
                    <div class="box-tools pull-right">
                        <!--                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                                                        <i class="fa fa-minus"></i></button>
                                                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                                                        <i class="fa fa-times"></i></button>-->
                    </div>
                </div>
                <div class="box-body">
                    <div class="column col-sm-12">

                        <h1><?= ($model->isNewRecord)? "Criar" : "Atualize" ?></h1>


                        <div class="col-sm-6 b-r">
                        <?= $form->field($model, 'nome')->textInput(['maxlength' => true]) ?>
                        <?php
                        if ($model->isNewRecord) {
                            echo $form->field($model, 'username')->label('login')->textInput(['maxlength' => true]);
                            echo $form->field($model, 'passwordHash')->label('Senha')->passwordInput(['maxlength' => true]);
                        }
                        ?>
                        <?=
                        $form->field($model, 'cpf')->widget(MaskedInput::classname(), [
                            'mask' => ['999.999.999-99']
                        ]);
                        ?>
                        <?=
                        $form->field($model, 'celular')->widget(MaskedInput::classname(), [
                            'mask' => ['(99)99999-9999']
                        ]);
                        ?>
                        </div>
                        <div class="col-sm-6 b-r">
                        <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
                        <?=
                        $form->field($model, 'arquivo')->label('Foto')->widget(FileInput::classname(), [
                            'options' => ['accept' => 'image/*'],
                        ]);
                        ?>
                        </div>
<?php ActiveForm::end(); ?>

                    </div>
                </div>
            </div>
        </section>
    </section>
</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'nome') ?>

    <?= $form->field($model, 'cpf') ?>

    <?= $form->field($model, 'username') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'celular') ?>

    <?php // echo $form->field($model, 'ativo') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/_search_1.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'passwordHash') ?>

    <?= $form->field($model, 'passwordResetToken') ?>

    <?php // echo $form->field($model, 'nivel_acesso') ?>

    <?php // echo $form->field($model, 'carteira_id') ?>

    <?php // echo $form->field($model, 'nome') ?>

    <?php // echo $form->field($model, 'cpf') ?>

    <?php // echo $form->field($model, 'celular') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'user_create') ?>

    <?php // echo $form->field($model, 'authKey') ?>

    <?php // echo $form->field($model, 'foto') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/create_1.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\User */

$this->title = Yii::t('app', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create User', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'password',
            'nome',
            'cpf',
            'username',
            //'email:email',
            //'celular',
            //'ativo',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/user/index_1.php
<?php

use yii\helpers\Html;
use app\models\Helper;
use kartik\widgets\DynaGrid;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\User */

$this->title = 'Usuário Lista';
?>
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Usuário
            <small>Lista</small>
        </h1>
        <ol class="breadcrumb">
            <!--<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Início</a></li>-->
        </ol>
    </section>

    <section class="content">
        <section class="content">
            <div class="box">
                <div class="box-header with-border">
                    <div class="form-group">

                    </div>
                    <div class="box-tools pull-right">
                        <!--                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                                                        <i class="fa fa-minus"></i></button>
                                                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                                                        <i class="fa fa-times"></i></button>-->
                    </div>
                </div>
                <div class="box-body">
                    <div class="column col-sm-12">
                        <?php
                            // View file rendering the widget
                            //http://demos.krajee.com/grid-demo
                            echo GridView::widget([
                                'dataProvider' => $dataProvider,
                                'filterModel' => $searchModel,
                                'pjax' => true, // pjax is set to always true for this demo
                                'bordered' => true,
                                'striped' => true,
                                'condensed' => true,
                                'responsive' => true,
                                'hover' => true,
                                'persistResize' => true,
                                'columns' => [
                                    'username',
                                    'email',
                                    'id',
                                    [
                                        'class' => 'yii\grid\ActionColumn',
                                        'header'=>'Ações',
                                        'headerOptions' => ['class'=>'cor-azul','width' => '80'],
                                        'template' => '{editar}{delete}',
                                        'buttons' => [
                                            'editar' => function ($url,$model) 
                                            {
                                                return Html::a('<i class="glyphicon glyphicon-pencil" title="Editar" data-toggle="tooltip"></i>', ['update','id'=>$model->id]).' ';
                                            },
                                            'delete' => function($url,$model)
                                            {
                                                $ativo = ($model->status)?["glyphicon-trash","Deletar"]:["glyphicon-repeat","Ativar"];
                                                return Html::a('<i class="glyphicon '.$ativo[0].'" title="'.$ativo[1].'" data-toggle="tooltip"></i>', ["delete",'id'=>$model->id]).' ';
                                            }, 
                                          ],
                                    ]  ],
                            ]);
                        ?>

                    </div>
                </div>
            </div>
        </section>
    </section>
</div>

    

views/user/recovery.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="login-box">
  <div class="login-logo">
    <?= Html::a('<b>Gerencie seu</b> Negócio',[''],['style'=>'font-size: 24px;']) ?>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Informe o E-mail para recuperar a conta</p>

    <?php $form = ActiveForm::begin([
                'id' => 'login-form',
                'class'=>'form-control'
            ]); ?>
            <div class="form-group has-feedback">
                <?= $form->field($model, 'email')->label(false)->textInput(['autofocus' => true]) ?>
                <span style="font-size: 30px;width: 70px;" class="ion ion-email form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-12 text-center">
                    <?= Html::submitButton('Recuperar', ['class' => 'btn btn-primary btn-block margin-top-10', 'name' => 'login-button']) ?>
                </div>
                <!-- /.col -->
            </div>
        <?php ActiveForm::end(); ?>
<!--    <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-social-icon btn-circle btn-facebook"><i class="fa fa-facebook"></i></a>
      <a href="#" class="btn btn-social-icon btn-circle btn-google"><i class="fa fa-google-plus"></i></a>
    </div>-->
    <!-- /.social-auth-links -->

    <div class="margin-top-30 text-center">
        <p>Já possui uma conta? <?= Html::a('Entrar',['default/index'],['class'=>'text-info m-l-5']) ?></p>
    	<p>Não tem uma conta? <?= Html::a('Inscrever-se',['user/register'],['class'=>'text-info m-l-5']) ?></p>
    </div>
    </div>
  <!-- /.login-box-body -->
</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Update User: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/update_1.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\User */
?>
<div class="user-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'password',
            'nome',
            'cpf',
            'username',
            'email:email',
            'celular',
            'ativo',
        ],
    ]) ?>

</div>